Zaka
Code-Hauptwache/Cpp_SoSe24_Hoffman pull request #7
Opened 2024-04-26 10:50 UTC by zakaBouj

2024-05-04 18:33 UTC, Yassin561 commented on zaka/worksheet3/task1/namespace.cpp
> -}
alles sieht rot bei mir aus , weis aber nicht warum

2024-05-04 18:33 UTC, Yassin561 commented on zaka/worksheet3/task1/namespace.cpp
> -}
ab zeile 3 bis 23

2024-05-04 21:44 UTC, zakaBouj commented on zaka/worksheet3/task1/namespace.cpp
> -}
ja das sieht bei mir auch so aus, liegt daran, dass ich diesen code entfernt habe, dann wird das rot angezeigt

2024-05-05 14:21 UTC, Yassin561 requested changes

2024-05-05 14:21 UTC, Yassin561 commented on zaka/worksheet2/exampleTasksLecture02/casting.cxx
MK an extra place for this type of excersisses

2024-05-09 16:35 UTC, Yassin561 approved these changes
sehr gut gemacht gehaltserhöhung gibst trotzdem nicht, du copek: int gehalt = equal pakistanische kind

2024-05-09 16:35 UTC, merged